### ISSUE TITLE
Installation crash on numpy version

### ISSUE THREAD

**Issue by nicojim** [minipief/pyva#1]
Hi,
I tried to install your package but failed with the error : 
ERROR: Could not find a version that satisfies the requirement numpy>=1.202 (from pyva)

1.202 does not seems to be a valid numpy version name. Numpy version are usually named as 1.XX.X

I could solve the problem on my PC by using the appropriate format for numpy version in the METADATA.

Fixe : in pyva-1.0-py3-none-any.whl/pyva-1.0.dist-info/METADATA
change the line 11 : Requires-Dist: numpy (>=1.202) to Requires-Dist: numpy (>=1.20.2)

**Comment by minipief** [comment]
Hi Nicolas,

thanks you for the information, this is really helpful. 
I will change this accordingly this evening and create a new wheel.

Best regards,

Alexander

**Comment by nicojim** [comment]
Thank you Alexander,

Didn't have the chance to test the package yet but it looks amazing!!

Best regards,
Nicolas

**Comment by minipief** [comment]
Updated wheel with correct numpy version added: 
Please use [pyva-1.0.0-py3-none-any.whl](https://github.com/minipief/pyva/blob/main/dist/pyva-1.0.0-py3-none-any.whl)
