### ISSUE TITLE
Some example issues on the instructions

### ISSUE THREAD

**Issue by LekoLabs-HsienTsungHu** [minipief/pyva#4]
Dear powerful pyva package creator, Herr Alexander Peiffer,

pyva is a great work for the acoustic and vibroacoustic. While I am recently working on the simulation software, I couldn't ignore your magnificent work.

After testing several things, I would like to open an issue and post some modifications. I wish you don't mind of those trifling remind and modifications.

_**Firstly**_
I would recommend that the installation way on [https://pyva.eu/index.html](https://pyva.eu/index.html) should use pip instead of wheel:
`git clone https://github.com/minipief/pyva.git`
path to pyva folder
`cd .../.../.../pyva`
then
`pip install .`

Otherwise, using _wheel_ might cause some incompleted installing situation. For example, **PoroElasticMat** in **pyva.properties.materialClasses** might not be imported with wheel.
I've checked it in python:
`import pyva.properties.materialClasses as matC`
and
`print(dir(matC))`

Also, once pyva was installed with wheel, it could be only uninstall in the terminal (virtual environment):
`sudo pip uninstall pyva`

_**Secondly**_
I would like to recommend some modifications on the example demonstration on [https://pyva.eu/index.html](https://pyva.eu/index.html)

Here are some correction and/or complementary for the examples **at [https://pyva.eu/system_classes.html](https://pyva.eu/system_classes.html)

### Acoustic Systems

**Acoustic Tubes**
Here's the result when I call "tube_elem", while they are a little bit different from what is shown on the website:
`>>> tube_elem`
`LinearMatrix of size (2, 2, 11), sym: 1`
`DataAxis of 11 samples and type angular frequency in 1 / second`
`resdof: DOF object with ID [1 2], DOF [1 1] of type [DOFtype(typestr='volume flow')]`
`excdof: DOF object with ID [1 2], DOF [0 0] of type [DOFtype(typestr='pressure')]`

**Membrane**
It was membrane, which should be Membrane:
`my_mem = ac1Dsys.Membrane(rubber,h,T,S)`

**Perforated Layer**
From 
`perf.plot(xdata,res='real')`
to
`perf.plot(omega,res='real')`

**Helmholtz resonator**
Change from resPure. to myResPure.
`Za_pure = myResPure.radiation_impedance(omega)` 
Change from resPerf. to myResPerf
`Za_perf = myResPerf.radiation_impedance(omega)`

Add a figure making command script
`plt.figure()`
`plt.plot(omega,np.real(Za_pure), color='blue', label = 'Re pure')`
`plt.plot(omega,np.imag(Za_pure), linestyle='dashed', color='orange', label = 'Im pure')`
`plt.plot(omega,np.real(Za_perf), linestyle='dotted', color='green', label = 'Re perf')`
`plt.plot(omega,np.imag(Za_perf), linestyle='-.', color='red',label = 'Im perf')`
`plt.xscale('log')`
`plt.legend(loc=4)`
`plt.show()`

**Quarter Wave Resonator**
Add a figure making command script
`plt.figure()`
`plt.plot(omega,np.real(Za_perf), color='blue', label = 'Re perf')`
`plt.plot(omega,np.imag(Za_perf), color='orange',label = 'Im perf')`
`plt.xscale('log')`
`plt.legend(loc=4)`
`plt.show()`

**Three Dimensional Acoustic Systems**
from 
`air = matC.Fluid()`
to
`>>> air = matC.Fluid()`

### Structure Systems

**Generic Two-Dimensional Plate System**
The term of "omega" is commonly and widely used but not indicated specifically for "angular frequency" and "frequency" in different examples.
For example here is frequency in Hz:
`omega = np.geomspace(100,10000)`
Then, it is changed to angular frequency:
`freq  = omega/2/np.pi`
Instead, in [https://pyva.eu/sea_models.html#sec-two-rooms](https://pyva.eu/sea_models.html#sec-two-rooms)
omega is used as:
`omega = mC.DataAxis.octave_band(f_max=2*np.pi*10000)`

A plotting script could be added for this example:
`plt.figure()`
`plt.plot(omega,rad_eff, color='blue', label = 'Leppington')` # Leppington is not as smooth as shown the website
`plt.plot(omega,rad_eff_simple, color='orange',label = 'ISO EN 12354-1')`
`plt.xscale('log')`
`plt.legend(loc=4)`
`plt.show()`

**The Rectangular Plate**
It was >>> N_max. The >>> could be removed.

When calling N_max, the result should be:
`array([18., 33.], dtype=unit32)`
but, the result is:
`array([10, 8], dtype=unit32)`

On the website, the w0 is defined as:
`w0 = rec_plate.w_modal_force(omega, N_max, 1., x0, y0, x0, y0)`
but it is defined as below in the function:
`w0 = rec_plate.w_modal_force(omega, N_max, 1., x, y, x0, y0)`

There's no value for x, y, x0, and y0 to correspond to the example demonstration.

A figure command would be recommended:
`plt.figure()`
`plt.plot(omega,np.real(w0), color='blue', label = 'Re w modal')`
`plt.plot(omega,np.imag(w0), color='orange',label = 'Im w modal')`
`plt.plot(omega,np.imag(w0_inf), color='green',label = 'Im w inf')`
`plt.xscale('log')`
`plt.legend(loc=4)`
`plt.show()`

**The Rectangular Plate : Discrete Method**
The HalfSpace class was not imported yet.
`import pyva.systems.acousticRadiators as aR`
air property is not defined also in this example or the previous parts.
`air = matC.Fluid()`
Then, it should be like:
`half_air = aR.HalfSpace(air)`

In the tau_modal, it was called as:
`tau_modal = rec_plate6mm.modal_transmission_coefficient_discrete(omega, (half_air, ),)`
but it should be as below, without 6mm:
`tau_modal = rec_plate.modal_transmission_coefficient_discrete(omega, (half_air, ),)`

A figure command would be recommended:
`plt.figure()`
`plt.plot(omega,TL_modal, color='blue', label = 'TL_modal')`
`plt.plot(omega,TL_inf, color='orange', label = 'TL_inf')`
`plt.xscale('log')`
`plt.legend()`
`plt.show()`

Also in the **The Rectangular Plate : Discrete Method** example:
when doing `mode_shapes.plot3d(4,1)`
It would be as following:
TypeError: FigureBase.gca() got an unexpected keyword argument 'projection'

_plot3d_ is from _ShapeSignal_ in pyva.data.matrixClasses

_**Lastly**_
The example at [https://pyva.eu/sea_models.html#sec-two-rooms](https://pyva.eu/sea_models.html#sec-two-rooms)

**Two rooms separated by a wall**
It was:
`power1mWatt = lC.Load(omega, 0.001*np.ones(omega.shape), pow_dof), name = '1mWatt')`
but it should be:
`power1mWatt = lC.Load(omega, 0.001*np.ones(omega.shape), pow_dof, name = '1mWatt')`

It was:
`two_rooms.add_load('1mWatt',power1Watt)`
but it should be:
`two_rooms.add_load('1mWatt',power1mWatt)`

After the plot and overlap plot, the result is not as shown as on the example demonstration

It was:
`sigma        = wall.radiation_efficiency(om_t,fluid = air)`
`sigma_simple = wall.radiation_efficiency_simple(om_t,fluid = air)`
while om_t is not defined, should it be _om_? :
`sigma        = wall.radiation_efficiency(om,fluid = air)`
`sigma_simple = wall.radiation_efficiency_simple(om,fluid = air)`

To plot the transmission loss with frequency, the equation should be added as:
`TL = -10*np.log10(tau)`

**Comment by minipief** [comment]
Hi Albert,

wow, this is a really demanding and helpful list. I did not like the wheel version and I suspected that there is another option for using the repository. However, I will check an change the documentation accordingly. Unfortunately, someone was earlier than me. So pip -install pyva is not possible.

As mentioned in my email, it will take a few weeks before I can implemented the improved documentation.

With best regards,

Alexander

**Comment by LekoLabs-HsienTsungHu** [comment]
Hello Alexander,

From me and my colleague's experience, wheel is no more a good tool. :(

I know there's a name conflict of pyva, so using `pip install pyva` cannot work.
_However_, people can use this script, `pip install .`, in the folder path where they clone/download pyva (acoustic).

For example:
(virtual env.)
`cd PATH` to where to put the pyva at local place.
`git clone _github link_`
`cd PATH/pyva` 
`pip install .`

Then, pyva is installed with the setup.py. :) 

Best regards,
Albert

**Comment by minipief** [comment]
Hi Albert,

I took some time to check the details.
However, I have some questions first. A fully agree with the weakness of the wheel option. I am still learning the code distribution with pyva.

I suppose your proposed solution installs the latest push of my changes - right?

What would be a good way to install stable releases that I created with the setup tool?

Regarding your comments:

- Thanks for the bug corrections in the documentation, I was not always precise.
- I try to stay with code snippets. Thus, I did not include all plot command to keep the text readable.
- Generic Two-Dimensional Plate System: The Leppington is exactly as in the pyva documentation. Are you using python 3.10 on windows???
-  TypeError: FigureBase.gca() got an unexpected keyword argument 'projection' ... that was a matplotlib issue .. corrected now. line changed to "ax = plt.axes(projection='3d')"
- The other bugs are corrected.

Thanks again for your remarks. This is really helpful because I don't have the time to check all things carefully. I will commit immediately. 

However, keep in mind I am currently updating the documentation for the poroelastic theory.

Best 
Alexander

**Comment by LekoLabs-HsienTsungHu** [comment]
Hello Alexander,

Thanks for your reply. I would say your pyva is a great achievement for the acoustic simulation and calculation.
I am 100% honest with you on this viewpoint.

I will reply to you below while yours are in italic.

_I suppose your proposed solution installs the latest push of my changes - right?_
Yes, I just created a venv to test it. Below is the following procedure:
1.	Create a venv.
2.	git clone pyva depository
3.	direct to the pyva root path
4.	‘pip install . ‘
5.	I’ve tested it with my code. I didn’t encounter any error. -> The bugs are all away.
_What would be a good way to install stable releases that I created with the setup tool?_
I use:
‘pip install git+https://github.com/minipief/pyva.git’ 

Or, we might consider using ‘docker’…? But it is not a very “simple” way to distribute and manage.

_Regarding your comments:_
_•	Thanks for the bug corrections in the documentation, I was not always precise._

Not at all. Again, your pyva is already a great acoustic simulation repository. 
Especially, it was a one-man work. Impressive.
As one of a user, I would signal those bugs for you. Don’t worry :)

Next time, a more wise way is that I will commit and push to the files in "doc/source/"

_•	I try to stay with code snippets. Thus, I did not include all plot command to keep the text readable._
I see. I know there’s an “example” folder in your repository, which is more complete.

_•	Generic Two-Dimensional Plate System: The Leppington is exactly as in the pyva documentation. Are you using python 3.10 on windows???_
I used python 3.10 on macOS (M1 MAX).
It’s only about the resolution:
from ‘omega = np.geomspace(100, 10000, 200)’ to ‘omega = np.geomspace(100, 10000, 1000)’ can fix.
Not a problem at all. Please ignore this part.

_•	TypeError: FigureBase.gca() got an unexpected keyword argument 'projection' ... that was a matplotlib issue .. corrected now. line changed to "ax = plt.axes(projection='3d')"
•	The other bugs are corrected._
Thank you so much for your time on the development. I will do a commit and push to do some signaling.


I might take too much time for those trifling errors. I could signal them because I am working in a private company, that I cannot commit some further developments.

Still, I will find some personal time to do some other development on pyva. :)
I need a while to do so. Wish you can understand.

Best regards,

**Comment by minipief** [comment]
Hi Albert,

thanks, this sounds great. If you intend to extend something specific feel free to ask and discuss.

I tried the ‘pip install git+[https://github.com/minipief/pyva.git’](https://github.com/minipief/pyva.git' option, but this also installed the latest release.
Is there an option that a distribution can be installed by directly assessing the wheel or other options with with a specific release number. This is to simply avoid that people install a 'construction version'

Best 
Alexander

**Comment by felipeacsi** [comment]
Hello,

this package and your book are awesome. Thanks for both of them.

Having said that, could you consider upload this package to PyPI with another name? Besides that, you can still preserve the `pyva` name for imports.

There is a popular package that does the same way: please see [PyPI - beautifulsoup4](https://pypi.org/project/beautifulsoup4/) (it uses `import bs4`) and [PyPI - bs4](https://pypi.org/project/bs4/).

As a long term solution to use `pip install pyva`, maybe you can consider to read [PEP 541](https://peps.python.org/pep-0541/). I don't know if this is a feasible solution.

Regarding:

> I tried the ‘pip install git+[https://github.com/minipief/pyva.git’](https://github.com/minipief/pyva.git' option, but this also installed the latest release. Is there an option that a distribution can be installed by directly assessing the wheel or other options with with a specific release number. This is to simply avoid that people install a 'construction version'

Yes. It is possible to install the package in various ways through this method. I think the best method would be to "tag" a release (through GitHub, git or other). If you need to tag an older commit (let's say after the book was published, for example, you can [follow these instructions](https://stackoverflow.com/a/4404197)). This way you can "name" releases and install it (not working at the moment) with:

`pip install git+https://github.com/minipief/pyva.git@v1.0.0`

There are more ways in [StackOverflow](https://stackoverflow.com/a/13754517).

Kind regards,

Felipe Raimann

**Comment by minipief** [comment]
Hi Felipe,Thanks for your positive feedback and remarks.And the answer ist yes, definitely. I am not happy with the current wheel solution and will carefully check your proposal and come back to you.Such remarks are very useful as I am not publishing packages all day :)Best AlexanderPS: Would you mind considering a book review wherever you bought the book. You could be the very first.Am 07.10.2023 01:44 schrieb felipeacsi ***@***.***>:
Hello,
this package and your book are awesome. Thanks for both of them.
Having said that, could you consider upload this package to PyPI with another name? Besides that, you can still preserve the pyva name for imports.
There is a popular package that does the same way: please see PyPI - beautifulsoup4 (it uses import bs4) and PyPI - bs4.
As a long term solution to use pip install pyva, maybe you can consider to read PEP 541. I don't know if this is a feasible solution.
Kind regards,
Felipe Raimann

**Comment by felipeacsi** [comment]
Yes, I will write one. I bought it on AbeBooks, so GoodReads would be the
best option.

Felipe

Alexander Peiffer ***@***.***> schrieb am Sa., 7. Okt. 2023,
3:15 AM:

**Comment by LekoLabs-HsienTsungHu** [comment]
Hello Alexander,

Sorry for my late reply.

I was going to say that you can tag the GitHub version as you want. Still, you need to maybe provide an instruction for the versions' releaseses.

There's also another option to control the version and the parts you would like to demonstrate, which is to use Docker. It's quite simple to distribute. 

Thanks also to @felipeacsi . I also learn from your info :)

**Comment by felipeacsi** [comment]
> PS: Would you mind considering a book review wherever you bought the book.

Done! https://www.goodreads.com/review/show/5901053831

I don't know how this works but currently it's not listed on the [book page](https://www.goodreads.com/book/show/59862348-vibroacoustic-simulation), unfortunately.

> There's also another option to control the version and the parts you would like to demonstrate, which is to use Docker. It's quite simple to distribute.

Hello @LekoLabs-HsienTsungHu!

Yes, that also could be possible, but I think Docker would be overkill for this package. I often see Docker to deploy web services with many packages of different "nature" in a remote machine. Python packaging is maybe a mess but I think the installation process should be kept as simple as possible.

**Comment by minipief** [comment]
Hi Felipe,Highly appreciated. Regarding pyva I think the best way is to tag specific stable versions and install from git as proposed by you.So the user might select if he would like to work with the current or a stable version.What do you think?BestAlexander Am 11.10.2023 06:54 schrieb felipeacsi ***@***.***>:

PS: Would you mind considering a book review wherever you bought the book.

Done! https://www.goodreads.com/review/show/5901053831
I don't know how this works but currently it's not listed on the book page, unfortunately.

There's also another option to control the version and the parts you would like to demonstrate, which is to use Docker. It's quite simple to distribute.

Hello @LekoLabs-HsienTsungHu!
Yes, that also could be possible, but I think Docker would be overkill for this package. I often see Docker to deploy web services with many packages of different "nature" in a remote machine. Python packaging is maybe a mess but I think the installation process should be kept as simple as possible.

**Comment by felipeacsi** [comment]
I think that would be ok. Though, if `pip` is the method to install, make it available from PyPI should be easy.

If you want, I can do a few tests to see how it works on test.pypi.org and I could write a couple of examples for "users" (stable releases) and "developers" (main branch of the git repo).

Please let me know if I can help in any way.

Felipe

**Comment by minipief** [comment]
The problem ist still the name conflict.I have not found a way to put it on pypi and keep pyva. If it will pyva1.0 but installed as pyva module, That would be great.BestAlexander Am 11.10.2023 08:07 schrieb felipeacsi ***@***.***>:
I think that would be ok. Though, if pip is the method to install, make it available from PyPI should be easy.
If you want, I can do a few tests to see how it works on test.pypi.org and I could write a couple of examples for "users" (stable releases) and "developers" (main branch of the git repo).
Please let me know if I can help in any way.
Felipe

**Comment by felipeacsi** [comment]
Let me put it this way: the name in PyPI is only for the installation with the `pip` command of PyPI. Then you import the package with the "package name" given in `setup.py` (`pyva`) with `import pyva` as usual.

Since `pyva` is currently used as a name in PyPI, we need an alternative. The most immediate option might be to choose a different name just for PyPI (this repository and the package will maintain the name).

I don't think `pyva1.0` would be valid as a name for PyPI because it has a version in its name. But if it is ok for you to choose another name just for PyPI, the package would still be installed as `pyva` (which I think is most important). Names for PyPI could be `pyva-toolbox` (or using *someword*: `pyva-*someword*`), `vibroacoustics`, `pyvibroacoustics`, `pyvacoustics`, etc.

I think `pyva-toolbox` (again, only for PyPI) could be an acceptable solution. Maybe in the future you can claim `pyva` in PyPI if the *other* `pyva` package remains inactive. What do you think?

Kind regards,

Felipe

**Comment by minipief** [comment]
Hi Felipe,This sounds reasonable. As the other packages are also toolboxes some acoustics in the title would be o.k.I will check this in the next days. Thanks a lot for your help.And I also will consider to claim it. I thought pyva is currently not really active.With best regards,AlexanderAm 11.10.2023 21:31 schrieb felipeacsi ***@***.***>:
Let me put this way: the name in PyPI is just for the installation with the pip command from PyPI. Then, you import the package with the "package name" stated in setup.py (pyva) with import pyva as always.
So, as pyva is currently taken as a name in PyPI, we need an alternative. The most immediate option could be to choose another name only for PyPI (this repository and the package maintain the name).
I think pyva1.0 as a name for PyPI wouldn't be valid, because it has a version in its name. But, if it is ok for you to choose another name only for PyPI, the package would still be installed as pyva (which I think is most important). Names for PyPI could be: pyva-toolbox (or whichever pyva-*something*), vibroacoustics, pyvibroacoustics, pyvacoustics`, etc.
I think pyva-toolbox (again, only for PyPI) could be an acceptable solution. Maybe in the future you can claim pyva in PyPI if the other pyva package remains inactive. What do you think?
Kind regards,
Felipe

**Comment by LekoLabs-HsienTsungHu** [comment]
> Let me put it this way: the name in PyPI is only for the installation with the `pip` command of PyPI. Then you import the package with the "package name" given in `setup.py` (`pyva`) with `import pyva` as usual.
> 
> Since `pyva` is currently used as a name in PyPI, we need an alternative. The most immediate option might be to choose a different name just for PyPI (this repository and the package will maintain the name).
> 
> I don't think `pyva1.0` would be valid as a name for PyPI because it has a version in its name. But if it is ok for you to choose another name just for PyPI, the package would still be installed as `pyva` (which I think is most important). Names for PyPI could be `pyva-toolbox` (or using _someword_: `pyva-*someword*`), `vibroacoustics`, `pyvibroacoustics`, `pyvacoustics`, etc.
> 
> I think `pyva-toolbox` (again, only for PyPI) could be an acceptable solution. Maybe in the future you can claim `pyva` in PyPI if the _other_ `pyva` package remains inactive. What do you think?
> 
> Kind regards,
> 
> Felipe

Hello Felipe, 

I am not an author though but I learned from your sharing.
Thanks a lot for that !

Best regards
